name: test
on:
 push:
  branches:
    - main
jobs:
 test_job:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v2
   - name: script
     run: |      
       ls
 checkout_job:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - run : mkdir path/artifacts
    - run : sampletext > path/artifacts/sample.txt
    
