name: test
on:
 push:
  branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  
jobs:
 test_job:
  runs-on: ubuntu-latest
  steps:
   - nmae: checkout
     uses: actions/checkout@v2
   - name: script
     run: |      
       ls