name: test
on:
 push:
  branches:
    - main
jobs:
 test_job:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v3
   - run : sampletext >> sample.txt  
   - uses: actions/upload-artifact@v3
     with:
      name: test-art
      path: sample.txt
   - name: script
     run: |      
       ls

    
