name: test1
on:
 push:
  branches:
    - main
jobs:
 test_job:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v2
   - name: script
     run: |      
       ls
